
import logging
from datetime import datetime
from pathlib import Path
from config import settings
from services.google_docs_service import GoogleDocsService

logger = logging.getLogger(__name__)

class ReportGenerator:
    def __init__(self):
        self.report_dir = Path(settings.output_dir).parent / "analysis_reports"
        self.report_dir.mkdir(parents=True, exist_ok=True)
        self.docs_service = GoogleDocsService()
    
    def create_report(self, job_data: dict) -> str:
        try:
            logger.info("Creating report")
            
            topic = job_data.get('topic', 'video')
            safe_topic = "".join(c for c in topic if c.isalnum() or c in (' ', '-', '_')).strip()
            safe_topic = safe_topic.replace(' ', '_')
            
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            report_file = self.report_dir / f"{safe_topic}_report_{timestamp}.txt"
            
            # Format content
            title = f"Video Generation Report: {job_data.get('topic', 'N/A')}"
            
            sections = f"""TITLE: {job_data.get('topic', 'N/A')}
STYLE: {job_data.get('style', 'N/A')}
STATUS: {job_data.get('status', 'N/A')}
GENERATED: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

SCRIPT:
{job_data.get('script_data', 'N/A')}

BLUEPRINT:
{job_data.get('blueprint_data', 'N/A')}

VIDEO PATH: {job_data.get('video_path', 'N/A')}
"""
            
            # Try Google Docs first
            doc_url = self.docs_service.create_doc(title, sections)
            
            if doc_url:
                logger.info(f"Google Doc created: {doc_url}")
                return doc_url
                
            # Fallback to local file
            logger.warning("Falling back to local report file")
            
            content = f"{title}\n\n{sections}\n\n---\nGenerated by Video Synthesis System"
            
            with open(report_file, 'w', encoding='utf-8') as f:
                f.write(content)
            
            logger.info(f"Local report created: {report_file}")
            return str(report_file)
            
        except Exception as e:
            logger.error(f"Report creation failed: {str(e)}")
            return None
